### ISSUE TITLE
Wrap errors

### ISSUE THREAD

**Issue by sah4ez** [sah4ez/now#23]
Need wrap errors for commands for more details.

**Comment by marti1125** [comment]
Hi @sah4ez I could help you :) Any idea how do you expect implement wrap error?

**Comment by sah4ez** [comment]
@marti1125 thank you!
The Idea it's simple, the each returned error in `./cmd/cli` need wrap with human readable cause of fail.
As example [there](https://github.com/sah4ez/pspk/blob/fdbeae23188c4f46208eb88819c816657f4510b3/cmd/cli/encrypt.go#L44) need add cause: `failed api load request`.

**Comment by sah4ez** [comment]
@marti1125 Hi! If you have a problems with code, you can ask me. If you can't implement this issue, write me, I'll try self.

**Comment by sah4ez** [comment]
closed #47
