### ISSUE TITLE
QR Code genration in CLI

### ISSUE THREAD

**Issue by sah4ez** [sah4ez/now#34]
add flag for generation QR codes for the publish command of pspk cli.

**Comment by marti1125** [comment]
@sah4ez  could be using this https://github.com/skip2/go-qrcode ?

**Comment by sah4ez** [comment]
yep https://github.com/sah4ez/pspk/blob/master/go.mod#L14
I used this package for generation QR codes [in web](https://github.com/sah4ez/pspk/blob/master/handler/index.go#L124).

**Comment by marti1125** [comment]
Hi @sah4ez this new feature is only create a new QR as image, like this example
https://gist.github.com/skip2/7e3d8a82f5317df9be437f8ec8ec0b7d

**Comment by sah4ez** [comment]
Yes, console pspk should work like [this](https://github.com/sah4ez/pspk/blob/master/handler/index.go#L124-L152). This code need move to the separate package and reuse in handler and cli commands.

**Comment by marti1125** [comment]
Hi @sah4ez after run
`./pspk --name helow publish --qr` <- for example
the image will create in the current path =?
actually response
Generate key pair on x25519

**Comment by sah4ez** [comment]
We have several scenarios work with QR code.
1. When we publishing key on the server, we can generate QR code
2. If we have generated key, we can create QR code for them
For the first case:
```
$ pspk --name <NAME> publish --qr 

Generate key pair on x25519
QR codes saved to ~/.local/share/pspk/<NAME>
```
it's ok, this command generate QR codes for private and public key and save them to the [directory of key](https://github.com/sah4ez/pspk/blob/master/pkg/evnironment/env.go#L12), also we should have option change path for saving files `--qr /path/to/directory`.
For the second case:
```
$ pspk --name <NAME> qr [--path]
or 
$ pspk --name <NAME> qr --with-private [--path]
```
,this command load exists keys and create for them qr codes to the  [directory of key](https://github.com/sah4ez/pspk/blob/master/pkg/evnironment/env.go#L12) or can save to the specific path from `--path`.

**Comment by marti1125** [comment]
If you are interesting https://www.bagevent.com/event/6368833/p/402890 is hackathon about COVID-19

**Comment by marti1125** [comment]
at 
`pspk --name <NAME> publish --qr `
I can not put a default value 
I got this error

run has error: flag needs an argument: -qr

so could be change that part =?

`pspk --name <NAME> publish --qr default ` or another name
default is a path

**Comment by sah4ez** [comment]
Hm... So, we can make `--qr` as flag and add string flag `--path` for saving with default values.
```
pspk --name <NAME> publish --qr
```
or 
```
pspk --name <NAME> publish --qr --path /path/to/qr/image
```

**Comment by marti1125** [comment]
Hi @sah4ez  sorry for big delay I sent a PR please check is a WIP

https://github.com/sah4ez/pspk/pull/49

**Comment by sah4ez** [comment]
https://github.com/sah4ez/pspk/releases/tag/v0.1.16
