### ISSUE TITLE
Not working name_regex query parameter

### ISSUE THREAD

**Issue by l-vitaly** [sah4ez/now#43]
**Describe the bug**

Not working `name_regex` query parameter

**To Reproduce**
1. Open terminal
2. Execute request curl "https://pspk.now.sh/?limit=10&name_regex=bob&output=json-array"

**Expected behavior**

One key is expected to be returned

**Comment by sah4ez** [comment]
@l-vitaly Oh... yes, it's worked not correctly.
For search for name by regex you can use only `name_regex`. `limit` and `output` don't work.
Also, `name_regex` always returning json format in response. 

I'll add support `limit` parameter in request.

**Comment by sah4ez** [comment]
Added support of `limit`.
```
> curl "https://pspk.now.sh/?name_regex=x1&limit=2" | jq .
[
  {
    "id": "5c952b5e149588f7c777c7b6",
    "name": "x1",
    "key": "wTaZA5+QeZpby33W2T5uV8TweWaPEZn3clTe5xkmb2M="
  },
  {
    "id": "5c954cf8149588f7c78fa747",
    "name": "x1p",
    "key": "QrV9sn60EqN9oy9NDuoTLyP7TGtPEuoo+O8kyA3QH1k="
  }
]
> curl "https://pspk.now.sh/?name_regex=x1&limit=2&last_key=5c954cf8149588f7c78fa747" | jq .
[
  {
    "id": "5c954cfd149588f7c78faae8",
    "name": "x2x1p",
    "key": "+PyHhXWOW01vg+b4VhAVqKNQdajwHYmsLnv31/114Rw="
  },
  {
    "id": "5c954d0f149588f7c78fb707",
    "name": "x3x1p",
    "key": "DTn42RAfS4WS77MZv+HSa/z8FXKXr1aS2/yOpySydQA="
  }
]
```

**Comment by sah4ez** [comment]
close by https://github.com/sah4ez/pspk/commit/dae7e3eb5fe5237aae37267e4d0d510f0f06ee85
