### ISSUE TITLE
Sign and verify  something

### ISSUE THREAD

**Issue by sah4ez** [sah4ez/now#5]
Add signing and verification of data through public key.

**Comment by sah4ez** [comment]
@marti1125 hi! How are you? How do you think about this feature, you can try do it, if  you have a leisure time. I can help you with implementation.

**Comment by marti1125** [comment]
Hi @sah4ez yep :) could you give an example or some tips ? thanks :)

**Comment by marti1125** [comment]
assign me :)

**Comment by sah4ez** [comment]
For [cli](https://github.com/sah4ez/pspk/blob/master/cmd/cli/main.go#L52) need add two new command:
```
pspk --name <KEY_NAME> sign message
pspk --name <KEY_NAME> sign --file <path_to_file>
pspk verify <PUBLIC_KEY_NAME> message
pspk verify <PUBLIC_KEY_NAME> --file <path_to_file>
```
This commands should work with signature/verification through ed25519.
Exists great package for this: https://github.com/agl/ed25519 and this implementation in [signal lib](https://github.com/RadicalApp/libsignal-protocol-go/blob/master/ecc/SignCurve25519.go). May be we can use this part in our project, just copy :-).

Be careful when put slice bytes for sign/verify, all input bytes need copy.

**Comment by marti1125** [comment]
Hi @sah4ez  please help https://github.com/sah4ez/pspk/pull/48

**Comment by sah4ez** [comment]
@marti1125 I merged your PR and added support of signature files:
https://github.com/sah4ez/pspk/releases/tag/v1.1.15

**Comment by marti1125** [comment]
awesome!! :+1:
